repos:
  - repo: https://github.com/pycqa/flake8
    rev: '6.0.0'
    hooks:  
      - id: flake8

  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
